### ISSUE TITLE
Parse Issue (Xcode): Module 'flutter_google_places_sdk_ios' not found

### ISSUE THREAD

**Issue by sarbogast** [matanshukry/flutter_google_places_sdk#12]
Lately, when I try to build a deployable version of my iOS app depending on version 0.3.2+1 of this package, I get the following error:

Parse Issue (Xcode): Module 'flutter_google_places_sdk_ios' not found
/Users/sarbogast/dev/synkro/staff/ios/Runner/GeneratedPluginRegistrant.m:35:8

I have tried everything, to flutter clean my project, deleted Pods and Podfil.lock manually, archiving directly from Xcode, and I always get the same error.

**Comment by matanshukry** [comment]
@sarbogast I remember I had that too, and I just had to clean up the iOS - although `flutter clean` wasn't enough.

iirc the commands I ended up running included `pod deintegrate`, or something like that. I hope it helps.

**Comment by matanshukry** [comment]
Closing since no feedback for some time now.
