### ISSUE TITLE
Feature request: language option

### ISSUE THREAD

**Issue by SylvainLosey** [matanshukry/flutter_google_places_sdk#14]
Hello,

First of all, thank you for building this plugin, the only one I found working correctly for web.

I wonder if you would consider adding a language option in one of the next releases ?

I thought about contributing a PR, but I think one would be needed for each of the platforms, so it might be easier to add it with other planned changes.

Bests,
Sylvain

**Comment by matanshukry** [comment]
Implemented passing the locale in web and released a new version, including a new sdk version using it.

**Comment by SylvainLosey** [comment]
Perfect thank you very much !
