### ISSUE TITLE
Flutter Web: You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors.

### ISSUE THREAD

**Issue by rscflexible** [matanshukry/flutter_google_places_sdk#16]
When I define my <script src="https://maps.googleapis.com/maps/api/js?key=apiKey"></script> in web/index.html to show Google Map on screen and everything work as expect but when I call a function to search place that use your package it's will show  "You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors." and then I can't use my moveCamera function at all (It's work before I calling  findAutocompletePredictions function). But when I use hot reload in android studio everything works without an error but stop and run will make it happen again

![Screenshot 2022-06-09 151153](https://user-images.githubusercontent.com/42487440/172798680-81652c80-db49-4d97-9acd-f97c66889758.png)

Second error is when I call moveCamera Function after calling  findAutocompletePredictions Function
Sorry for my bad English I hope you can help me. 
Thank You.

**Comment by matanshukry** [comment]
@rscflexible Can you provide a reproducible example?

**Comment by rscflexible** [comment]
When I have google map api key store in project/web/index.html
![1](https://user-images.githubusercontent.com/42487440/173040201-b4f375db-8c42-4369-8fb2-d9d661117183.png)

and I call this function when I press  search button in MapScreen 
![2](https://user-images.githubusercontent.com/42487440/173040264-1e2f120e-f645-4cf2-84f8-ed251ec363a2.png)

It will show "You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors." in browser console and android studio debug console (But I got the google place predictions result fine)
![image](https://user-images.githubusercontent.com/42487440/173040328-fbc424d1-c471-4412-b828-e8768fbe2db6.png)

After that warning when I use move camera function in MapScreen. The camera will not move to target LatLng even if I set fixed LatLng value to it( It works before I call function in second image)
![3](https://user-images.githubusercontent.com/42487440/173040781-c408fa0a-9286-450d-87d8-1673e04e624e.png)

 And It will show this error in browser console also 
![image](https://user-images.githubusercontent.com/42487440/173041010-4111e4d2-a007-4906-97b0-c7d28254224a.png)


But if I remove google map api key that store in /web/index.html and use function in second image it will not get the errror but then I can't display google map on my MapScreen

Thank you for your fast response.

**Comment by matanshukry** [comment]
@rscflexible I need a reproducible example - not just screenshots and code snippets. some repository I can clone and run and it will show the same error.

I tried replicating it on my own but it works - I got an index.html file with the added `maps/api/js` link like you wrote, and I can still run the search from this package.

**Comment by rscflexible** [comment]
https://github.com/rscflexible/map_test.git

Your search function work fine here too but somehow I don't know why it make CameraUpdate unusable for me. I can't move camera to other location after use search function.

The problem only occur when you run it for the first time or stop the web and run it again but if you're hot reload it in android studio everything will work fine without warning or error and CameraUpdate will work after use search function

**Comment by matanshukry** [comment]
@rscflexible sure, you just need to make sure the GoogleMap widget will be built after the places is initialized. You can use a future builder and the `.isInitialized` method with the returned future:

class variables:
```
  late place.FlutterGooglePlacesSdk _places;
  late Future _placesInitFuture;
```

initState:
```
  @override
  void initState() {
    super.initState();

    _places = place.FlutterGooglePlacesSdk('apiKey');
    _placesInitFuture = _places.isInitialized();
  }
```

and instead of using `GoogleMap` widget directly, use:
```
              FutureBuilder(
                  future: _placesInitFuture,
                  builder: (context, snapshot) {
                    if (snapshot.connectionState == ConnectionState.done) {
                      return GoogleMap(
                        myLocationButtonEnabled: false,
                        initialCameraPosition: CameraPosition(
                          target: LatLng(lat!, lng!),
                        ),
                        mapType: MapType.normal,
                        onMapCreated: _onMapCreate,
                        myLocationEnabled: false,
                      );
                    }
                    return const CircularProgressIndicator();
                  },
              ),
```

**Comment by rscflexible** [comment]
@matanshukry  Your solution is working. Thank you very munch for helping me out and for your hard work that you put  into this wonderful google place package.

**Comment by matanshukry** [comment]
@rscflexible you welcome!

**Comment by ZacharyHandshoe** [comment]
> @rscflexible sure, you just need to make sure the GoogleMap widget will be built after the places is initialized. You can use a future builder and the `.isInitialized` method with the returned future:
> 
> class variables:
> 
> ```
>   late place.FlutterGooglePlacesSdk _places;
>   late Future _placesInitFuture;
> ```
> 
> initState:
> 
> ```
>   @override
>   void initState() {
>     super.initState();
> 
>     _places = place.FlutterGooglePlacesSdk('apiKey');
>     _placesInitFuture = _places.isInitialized();
>   }
> ```
> 
> and instead of using `GoogleMap` widget directly, use:
> 
> ```
>               FutureBuilder(
>                   future: _placesInitFuture,
>                   builder: (context, snapshot) {
>                     if (snapshot.connectionState == ConnectionState.done) {
>                       return GoogleMap(
>                         myLocationButtonEnabled: false,
>                         initialCameraPosition: CameraPosition(
>                           target: LatLng(lat!, lng!),
>                         ),
>                         mapType: MapType.normal,
>                         onMapCreated: _onMapCreate,
>                         myLocationEnabled: false,
>                       );
>                     }
>                     return const CircularProgressIndicator();
>                   },
>               ),
> ```

This solved my issue. I was having a near identical problem. I was porting my Google Maps implementation to Flutter Web utilizing [google_maps_flutter_web](https://pub.dev/packages/google_maps_flutter_web).

I fixed it by removing the `google_maps_flutter_web` package and line 
```
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR API KEY"></script>
```
 from my index.html file, and following the quoted instructions.
