### ISSUE TITLE
Feature Request: Add iOS Support

### ISSUE THREAD

**Issue by LucaDillenburg** [matanshukry/flutter_google_places_sdk#3]
Hello @matanshukry , 
I loved the rational behind the package and believe this also solves the CORS issue on Flutter Web, right?
Anyway, my Flutter app is rolling out for Android, iOS and the web. Is there any chance iOS support will be added soon? I have no experience with iOS development nor Flutter platform channels so I'm afraid I wouldn't be able to help.

**Comment by matanshukry** [comment]
@LucaDillenburg Added support to it.
