### ISSUE TITLE
Restrict the api on mobile iOS and android exception even using the sdk throwing this exception 

### ISSUE THREAD

**Issue by farahfarah1** [matanshukry/flutter_google_places_sdk#34]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(API_ERROR_AUTOCOMPLETE, 9011: This IP, site or mobile application is not authorized to use this API key. Request received from IP address *********, with empty referer, {type: class com.google.android.gms.common.api.ApiException}, null)

**Comment by naw2nd** [comment]
any solution about this? i facing the same problem... pls help @farahfarah1
