### ISSUE TITLE
[Question] Why the address field for web platform  is not consistent with the other platforms?

### ISSUE THREAD

**Issue by mrcsilverfox** [matanshukry/flutter_google_places_sdk#40]
On Android and iOS the place field `Address` is mapped with `Place.Field.ADDRESS` and `formattedAddress` respectively.
On Web platform it is mapped with `add_address`, why? The `formattedAddress ` is also available for this platform
[Ref](https://developers.google.com/maps/documentation/places/ios-sdk/place-data-fields#basic)

**Comment by matanshukry** [comment]
@mrcsilverfox thanks for the contribution! I've merged the PR and published the new web version 🙇
