### ISSUE TITLE
[FeatureRequest] fetchPlace on MacOS

### ISSUE THREAD

**Issue by AndreiMisiukevich** [matanshukry/flutter_google_places_sdk#44]
Hello, first of all, thanks for your outstanding contributions to the open source.

But I have a question / feature request.

Any reason why `fetchPlace` is not implemented in `flutter_google_places_sdk_http.dart`?

```dart
  @override
  Future<inter.FetchPlaceResponse> fetchPlace(
    String placeId, {
    List<inter.PlaceField>? fields,
    bool? newSessionToken,
  }) async {
    throw UnimplementedError();
  }
  ```

**Comment by matanshukry** [comment]
@AndreiMisiukevich the http implementation is a bit new, so it was just never done - no technical reason or something like that.

PRs are welcome though.

**Comment by AndreiMisiukevich** [comment]
CC @matanshukry

**Comment by sarbogast** [comment]
So if I understand correctly, given that the feature was never merged, fetchPlace still doesn't work on macOS, right?
Because I still get an UnimplementedError

**Comment by AndreiMisiukevich** [comment]
@sarbogast yes, that's correct
I switched to using API directy - https://maps.googleapis.com/maps/api/place
