### ISSUE TITLE
FlutterGooglePlacesSdk::call error: UnimplementedError: initialize() has not been implemented.

### ISSUE THREAD

**Issue by huesmiles49** [matanshukry/flutter_google_places_sdk#60]
This is my current code:
`final FlutterGooglePlacesSdk _places =
      FlutterGooglePlacesSdk(FlavorConfig().googlePlacesApiKey);`
 
```
 FindAutocompletePredictionsResponse res =
        await _places.findAutocompletePredictions(_searchText);
    print(res);
    setState(() {
      _predictions = res.predictions;
    });```

When I type a text in the TextField to request the predictions, the package is returning this error: 
`FlutterGooglePlacesSdk::call error: UnimplementedError: initialize() has not been implemented.`

**Comment by huesmiles49** [comment]
My other attempt to initialize the package doesn't work either. Code:
```
final places = FlutterGooglePlacesSdk.platform;
    places.initialize(FlavorConfig().googlePlacesApiKey);
    FindAutocompletePredictionsResponse res =
        await places.findAutocompletePredictions(_searchText);
    setState(() {
      _predictions = res.predictions;
    });
   ```
<img width="1180" alt="Screenshot 2023-09-26 at 4 31 39 PM" src="https://github.com/matanshukry/flutter_google_places_sdk/assets/16810280/cf6aaa9a-2c3a-442c-94ab-2427ea5db82c">

**Comment by matanshukry** [comment]
@huesmiles49 Looks like something is wrong with the dependencies. Take a look at the example in this project and use it.

If you still have issue, please create a small reproducible example that we can work.

**Comment by huesmiles49** [comment]
System: Mac - Ventura 13.0.1
Flutter Version: 3.13.0
Platform: Flutter web

I'm unable to reproduce the issue. It seem to happen randomly. This is the first time I'd experience the issue directly. Another time was when the same problem happen to my coworker. So far, we've only seen this issue on Flutter web.

The only way I know to fix this problem is:
- run this command `dart pub cache clean`
- then run the app
- then either check or uncheck the `Uncaught Exception` in VSCode debugger
- then hard reset the app
This seems to reset the initialize function when setting the Google Place API key.

To conclude, I applied the fix mentioned and the package is working again.

**Comment by matanshukry** [comment]
@huesmiles49 it sounds like flutter dependencies/caching issues.

But either way glad to hear it's working again!
