### ISSUE TITLE
Error saying package has missing methods

### ISSUE THREAD

**Issue by covacialex** [matanshukry/flutter_google_places_sdk#62]
I've used this package on another project a few months ago and has been working perfectly fine. Now that I've started a new project and wanted to import the code I wrote on the older one, the app crashes on startup. I've tried starting brand new clear projects with just this package installed and I still get the same error. I've asked my colleague to do the same, and he gets the same error.

![image](https://github.com/matanshukry/flutter_google_places_sdk/assets/96472252/a4977cdb-8ed0-40c9-9a0a-93b81bc23526)

This is what I have inside the package: 

![image](https://github.com/matanshukry/flutter_google_places_sdk/assets/96472252/b8b7aa8b-1670-4f53-a237-a7c760bde203)

**Comment by matanshukry** [comment]
@covacialex I tried the example from this package again, while using the public version (0.3.7) and it works. To clarify, I used the termina:
```
flutter clean
flutter build web
flutter run -d edge
```

If it still doesn't work for you, please upload a reproducible example I can download and run (or rather try to run, and get the same error as you).

**Comment by covacialex** [comment]
@matanshukry Thanks for the quick reply. I've copied and pasted what was missing inside the package from my previous project for a quick workaround. Now I've tried to reproduce the same error but it works just fine. I have absolutely no idea what could've been the problem. Probably some hidden caching? Although I cleared the cache with the terminal as well as deleted the whole folder, beats me.
