### ISSUE TITLE
Flutter web deploy issue on aws

### ISSUE THREAD

**Issue by adnan-haider007** [matanshukry/flutter_google_places_sdk#64]
i implement this pacakge in flutter web but when i try to deploy on aws then it will this error appear 

<img width="324" alt="image" src="https://github.com/matanshukry/flutter_google_places_sdk/assets/100688949/e2b7a04f-187c-485c-add7-e233c902657b">

this happens when i use flutter package without version 

but  i am using latest version flutter_google_places_sdk:0.3.7 then this happens 

<img width="1137" alt="image" src="https://github.com/matanshukry/flutter_google_places_sdk/assets/100688949/4d8eb1c0-611e-4828-bc2d-e5b254d24ab1">

**Comment by matanshukry** [comment]
@adnan-haider007 I believe that's caused because you're using an older version of flutter.

It's the same reason I can't update the `collection` package to 1.18 btw; latest flutter test package only supported 1.17.2 (at least at the time).
