### ISSUE TITLE
Crash on iOS

### ISSUE THREAD

**Issue by bw-flagship** [matanshukry/flutter_google_places_sdk#7]
Thanks a lot for this awesome plugin!
Sadly i get a crash on iOS when I try to get autocomplete predictions.
The app immediately shuts down. I made sure that the key works, this cannot be the problem.
Do you have any idea?
Thanks!

Output:
Could not cast value of type 'NSNull' (0x2013b71a8) to 'NSNumber' (0x2013b78b8).
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001dac777b0 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1dac777b0 <+8>:  b.lo   0x1dac777cc               ; <+36>
    0x1dac777b4 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1dac777b8 <+16>: mov    x29, sp
    0x1dac777bc <+20>: bl     0x1dac541fc               ; cerror_nocancel
Target 0: (Runner) stopped.
Lost connection to device.

**Comment by bw-flagship** [comment]
i just figured out that this occurs if newSessionToken is not provided.
If i set newSessionToken to true or false, it works.

**Comment by ZacharyHandshoe** [comment]
Hello, I have a similar issue, are you using firebase and/or firestore by any chance? I have conflicting dependencies currently causing these issues.

**Comment by bw-flagship** [comment]
@ZacharyHandshoe my issue had nothing to do with dependencies, I could reproduce it with a minimal sample

**Comment by matanshukry** [comment]
Fixed in version 0.3.1: https://pub.dev/packages/flutter_google_places_sdk/versions/0.3.1
