### ISSUE TITLE
Add location constraints

### ISSUE THREAD

**Issue by sperochon** [matanshukry/flutter_google_places_sdk#8]
Hello, thanks for your plugin!

Could you please add following constraints?
```
setLocationBias
setLocationRestriction
```
https://developers.google.com/maps/documentation/places/android-sdk/autocomplete#bias_results_to_a_specific_region

Thanks!

**Comment by matanshukry** [comment]
Implemented and available in 0.3.1: https://pub.dev/packages/flutter_google_places_sdk/versions/0.3.1

Note: web does not currently support location restriction.
https://issuetracker.google.com/issues/36219203

**Comment by sperochon** [comment]
👍😃 Thanks for the speed! I'm gonna try it!

**Comment by sperochon** [comment]
Works perfectly fine! 👍 I've post a message on Google issue about location restriction unavailability. Thanks again!
