### ISSUE TITLE
Add Support for Google Places (New)

### ISSUE THREAD

**Issue by Agyapaldhiman** [matanshukry/flutter_google_places_sdk#84]
Google Places has since updated their SDK and now call this new version [Google Places (new)](https://developers.google.com/maps/documentation/places/web-service/op-overview). It adds a new text search API.

Kindly look into this.

**Comment by flikkr** [comment]
Hi @Agyapaldhiman, can you close this issue since its tracked in #77?

**Comment by Agyapaldhiman** [comment]
Ok sure

**Comment by Agyapaldhiman** [comment]
closing this issue
